name: 'Hello World'

runs:
  using: "composite"
  steps:
    - run: echo Hello .
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-number::$(echo $RANDOM)"
      shell: bash
