# This workflow will build from your source code, publish and deploy it to your OpenShift cluster
#
# To configure this workflow:
#
# 1. Setup secrets in your repository by going to settings
# 2. Ensure you are using the correct oc version
# 3. Change the values for the APPNAME and PROJECT

name: Build and Deploy to OpenShift
on: [push]

env:
  PROJECT: hello-world
  APPNAME: myapp

jobs:
  build:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: OpenShift Action
      uses: redhat-developer/openshift-actions@v2.1.0
      with:
        version: '4.3'
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        parameters: '{"apitoken": "${{ secrets.API_TOKEN }}", "acceptUntrustedCerts": "true"}'
      cmd: |
        oc project ${PROJECT}
        oc new-build ${GITHUB_WORKSPACE} --name=${APPNAME} --strategy=source --to=${APPNAME}:latest
        oc start-build ${APPNAME} --from-dir ${GITHUB_WORKSPACE} --follow
        oc new-app ${PROJECT}/${APPNAME}:latest ## this can be removed after the first deploy - 
                                                ## it will create a deploymentconfig which will trigger a new deploy after a new build
        oc expose svc/"${APPNAME}" ## this can be removed after the first deploy