name:nuild-source-code

on:
  push:
    branches:[main]

jobs:
  build:
    runs-on: ubuntu-lates
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
    - uses: actions/setup-java@3.3.0
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

