# This workflow shows you how the action can download the oc bundle from any URL
#
# To configure this workflow:
#
# 1. Ensure that the URL where oc can be downloaded exists
# 2. Setup secrets in your repository by going to settings
# 4. Change the values for the APPNAME, DOCKERIMAGE and PROJECT

name: Download oc from url
on: [push]

env:
  PROJECT: hello-world
  DOCKERIMAGE: node:10
  APPNAME: myapp

jobs:
  build:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: OpenShift Action
      uses: redhat-developer/openshift-actions@v2.1.0
      with:
        version: 'https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz'
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        parameters: '{"apitoken": "${{ secrets.API_TOKEN }}", "acceptUntrustedCerts": "true"}'
      cmd: |
        oc project ${PROJECT}
        oc new-build --strategy docker --binary --docker-image ${DOCKERIMAGE} --name ${APPNAME}
        oc start-build ${APPNAME} --from-dir . --follow
        oc new-app ${PROJECT}/${APPNAME}:latest
        oc expose svc/"${APPNAME}"