
name: CI
on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        type: string   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/hello
        with:
          who-to-greet: ${{ secrets.JO_JO }}
      - uses: zhouzhou96/JavaDemo/.github/workflows/reusing.yml@main



