
name: CI
on:
  workflow_dispatch:
    inputs:
      string:
        required: true
        type: string
      
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Push to ECR
        run: |
          echo "steps.extract_branch.outputs.branch ---- ${{ steps.extract_branch.outputs.branch }}"
          echo "github.ref_name ---- ${{ github.ref_name }}"
          exit 1
          echo "github.event.inputs.string  -----  ${{ github.event.inputs.string }}"
        

