
name: CI

on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        type: string



jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      
      - uses: ./.github/actions/hello
        with:
          who-to-greet: ${{ secrets.JO_JO }}
  ss:
      uses: ./.github/workflows/reusing.yml
      with:
        username: ${{ github.event.inputs.username}}
      secrets:
          envPAT: ${{ secrets.envPAT }}


