
name: CI
on:
  workflow_dispatch:
#    inputs:
#      username:
#        required: true
#        type: string   
jobs:
  call-reusing:
    uses: zhouzhou96/JavaDemo/.github/workflows/reusing.yml@main
  call-reusing1:
    uses: zhouzhou96/JavaDemo/.github/workflows/reusing1.yml@main
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/hello
        with:
          who-to-greet: ${{ secrets.JO_JO }}
          run:
           echo '2222222222222222222' 





