name: Reusable workflow example

on:
  workflow_dispatch:
  workflow_call:
        
jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - name: console_log
        run: |
          echo "00000000000000000000000"
